PASSWORD = "otsu1521"

[gcp_service_account]
type= "service_account"
project_id= "poised-beach-443202-j0"
private_key_id= "f5c4afe85cfb90bace27ac61eebf6d29c6d6cf51"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdmQsd5rinOVnC\nYahTIWH10vf3mzwfLitDrrbFtiW4PGFSL66fGROhgdLb/ho0jWzIqwR/mWU8cKYy\nzDsqb1BywdqE8AiqGRG/lrvmVqDuFIb3uQ+eQIzPn0N8BT3DGQaqCfPgVAvKqO+T\nCicNxBYvy5bG/X1SB/ik8Av80Wz7UY1fjSG+WHNg3I2+T0grUeEkwvP9BSmXNfPP\nRWA5xtubUpq2/JKyCGT3bP+mUfGRGkejOfCwO/0oDtNmMw0GBleGQ2KZB4PMDz7f\ni8qWTA2cUx0zPlTbbq0wPNQ+3ah9zqlNoAsyYGEWhpxpobwfZiTcBVQLy6xA8pHB\nymj2wCHlAgMBAAECggEAG30oqH5IOpjhDGv6z4c83kM+b9DCr6CeuMdGh51yHlzf\nz9VT1Nnrp+nsZOWBXiXF8gmMdxJDS4PNpYIkls4EPwQLsNDqffrx8tRgsXhuSSDI\n+vgrXnvdY9CglYcXgwqANFQYlwop5V9KrH/imH7ZrNwK0GpCO/b6epCJUr+Xzg0h\nMooPAdjHNxhMUcFFfimazDFYkb7N3sZYdnwF+jmr9ev2oAYFS2rnjk83yDweqTrE\nmgpmk1cguh5RkrmhH8rCiI0lb8h2y6h6m57Ouo6Sm2kt4+Z3RnI8DUG9bxT+8Tag\n1SHfPvUWJpG3TNz6oi8SISO5vt+kaHnEdzoMwky44QKBgQDMAcSZNJ7t1IfJVLQr\nOVscr5jFbxrfw0l6OVCB6wVaSXOzAOKnsBTEziGjo5qb1fYafzbIHeXMQXrjzFea\nn2RH9C/p0giU26CIFM7RKOptKO39BsV/Ut05dl4jiJ7hac+QxhpEZngHieeDRuE6\nsDw60yRb2BnKHKHm28LwoiaiBQKBgQDFw1w1elxxLWkhr3spUdsn0+Weu7Q/TO89\nsHBJZj0xW3UWwHYN2BMaH7nGUc4veoL7kY5jv/1LJb3CaypL7EJwa8KdpXHzdz4j\ns3SDjjds/8rhdJeIjEHqybaWlMn+e8+1HmzNtBmjYwxxiBq3oxezQ3vGnLTT22H2\nllwIbtAmYQKBgGs0FqLHsyiZgY179H2uU0G8yNQfcYjar5cJ3VOYNCTg6mrLcU/b\nSN6uz6CVTZ7MjdoYtanthB+U3UYt0G9RiToCiNcfZyEKVM6N2KyzCpW4Z2+KimhB\nHD2hBRE5LvyXRNr4Lz94dWTIxB8JNTxI9i2XXMjiw5Kg/zc4jrUzEIgdAoGAZlpx\nG+CDfbQSCHQpGz6ZXaim3Bur82MfI19xDhwTKbt7A1aDAzFE2a132fO28g3HQuqX\ntnrEXqNe7gPG9VqHHGY5aJwbOPYLPDEB6aCugQR2fW95ihuFdj4F+TNyw/pSixv/\nFgvThSObahsWMNsBRi90HVw3nrqZniU95sNriaECgYEAsN3IZdKa2g3VTVCkUCPP\nhbcHMx2opZM7tsnRQjegU1ykO/BG/+kiNK4EBQIbWxGsqBV3HbioBVicptU/rpsg\nAsqTl40TYvDh64PKTqLAaRjfqtr5kmSubl+qzaRUpL1aBMUTR2Zs56dOMW8vp5P3\nDdoY0QTHLPEYzw4xJAe1nuc=\n-----END PRIVATE KEY-----\n"
client_email= "service-account-jusk653s@poised-beach-443202-j0.iam.gserviceaccount.com"
client_id= "108530902960075452730"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/service-account-jusk653s%40poised-beach-443202-j0.iam.gserviceaccount.com"
universe_domain= "googleapis.com"

[connections.supabase]
# db接続用
dialect = "postgresql"
host = "aws-1-ap-northeast-1.pooler.supabase.com"
port = "6543"
database = "postgres"
username = "postgres.sfpgvvwissengkvxjrrn"
pool_mode= "transaction"
password = "gan5qKpRua1bA00R"

# Auth用
project_url = "https://sfpgvvwissengkvxjrrn.supabase.co"
key = "sb_publishable_3k9wUVw8Sv74j4YzKCHu6g_-m0sPrAz"